igor/InvoiceCreator/grails-app/domain/com/genrep/invoiceRepository/InvoicePurchaseArchive.groovy
package com.genrep.invoiceRepository

import com.genrep.domain.AInvoice
import com.genrep.invoiceCreator.ExchangeRate
import com.genrep.vendor.Vendor

class InvoicePurchaseArchive extends AInvoice {

    static constraints = {
        admissionCounterNumber nullable:true, validator: { value, domain->
            if(!domain.isProInvoice){
                return value!=null
            }
        }
        admissionCounterNumberView nullable:true, unique: true, validator: { value, domain->
            if(!domain.isProInvoice){
                return value!=null
            }
        }
        docMongoId()
        invoiceNumber()
        invoiceCounter(nullable: true)
        invoiceYear()
        swiftCode(nullable: true,blank: true)
        client(nullable: true)
        vendor()
        totalSum()
        taxPriceSum()
        taxFreeSum()
        taxes(nullable: true)
        inCurrency()
        exchangeRate(nullable: true)
        documentFile(minSize: 1) // minSize=1 because we don't want to allow empty byte array
        documentName()
        issueDate()
        dateCreated()
        paymentDate(nullable: true)
        paidOnDate(nullable: true)
        invoiceDescription(nullable: true, blank: true)
        isProInvoice()
        refInvoice(nullable: true)
        paymentPercentage(nullable: true)
    }

    static mapWith = "mongo"

    static mapping = {
        collection "InvoicePurchaseArchives"
//        database "InvoiceRepository"
//        sort issueDate: "desc"
        sort([invoiceYear:'desc', admissionCounterNumber:'desc'])
    }

    Long admissionCounterNumber
    String admissionCounterNumberView

    String docMongoId = UUID.randomUUID()
    BigDecimal totalSum
    BigDecimal taxPriceSum
    BigDecimal taxFreeSum

    Map<Taxes,BigDecimal> taxes

    Currency inCurrency
    ExchangeRate exchangeRate
    // Instead of Client
    Vendor vendor

    byte [] documentFile
    String documentName
    String invoiceDescription

    Date dateCreated
    Date paymentDate
    Date paidOnDate

    BigDecimal paymentPercentage


    // ProInvoice features
    boolean isProInvoice = false
    // String refInvoice                       // Reference to ProInvoice. ComboBox of ProInvoice numbers
    InvoicePurchaseArchive refInvoice          // Reference to ProInvoice. ComboBox of ProInvoice numbers

    def beforeInsert(){
        issueDate = issueDate.clearTime()
    }
    def beforeUpdate(){
        if(this.isDirty('issueDate')) {
            issueDate = issueDate.clearTime()
        }
    }

    def beforeDelete(){
        if(refInvoice!=null){
            def ref = findWhere(id: refInvoice.id)
            if(ref){
                ref.refInvoice = null
                ref.save()
            }
        }
    }

    def afterInsert(){
        if(!isProInvoice && refInvoice!=null){
            def proInvoice = findWhere(id: refInvoice.id)
            if(proInvoice){
                proInvoice.refInvoice = this
                proInvoice.save()
            }
        }
    }

    static String createAdmissionCounterNumberView(Long year, Long counter){
        if(counter == null){
            return null
        }
        return counter.toString().concat("/").concat(year.toString())
    }
}

igor/InvoiceCreator/grails-app/controllers/com/genrep/invoiceRepository/InvoicePurchaseArchiveController.groovy
package com.genrep.invoiceRepository

import com.genrep.invoiceCreator.Money
import grails.converters.JSON
import org.springframework.web.multipart.MultipartHttpServletRequest

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class InvoicePurchaseArchiveController {

    static allowedMethods = [save: "POST", update: "POST", delete: "DELETE"]

    def documentFileService
    def invoiceCounterService
    def invoiceService

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        def customSortFields
        if(params.sort && params.sort.contains(",")){
            customSortFields = params.sort.split(",")
        }
        def list = InvoicePurchaseArchive.createCriteria().list{
            if(customSortFields){
                customSortFields.each {
                    order(it,params.order)
                }
            }
            else if(params.sort && params.order){
                order(params.sort,params.order)
            }
            else{
                order('invoiceYear','desc')
                order('admissionCounterNumber','desc')
            }
            if(params.offset){
                firstResult params.offset as int
            }
            if(params.max){
                maxResults params.max
            }
        }
//        respond InvoicePurchaseArchive.list(params), model: [invoicePurchaseArchiveInstanceCount: InvoicePurchaseArchive.count()]
        respond list, model: [invoicePurchaseArchiveInstanceCount: InvoicePurchaseArchive.count()]
    }

    def show(InvoicePurchaseArchive invoicePurchaseArchiveInstance) {
        respond invoicePurchaseArchiveInstance
    }

    def newImport() {
        params.admissionCounterNumber = invoiceCounterService.getPurchaseInvoiceCounter()
        List<InvoicePurchaseArchive> proInvoices = InvoicePurchaseArchive.findAllByIsProInvoiceAndRefInvoice(true,null)
        render view: 'newImport',
                model: [invoicePurchaseArchiveInstance:new InvoicePurchaseArchive(params),
                        proInvoices: proInvoices
                ]
    }

    @Transactional
    def save(InvoicePurchaseArchive invoicePurchaseArchiveInstance) {

        if (invoicePurchaseArchiveInstance == null) {
            notFound()
            return
        }

        Long invoiceYear = Long.parseLong(params.admissionYear_year)
        invoicePurchaseArchiveInstance.invoiceYear = invoiceYear
        invoicePurchaseArchiveInstance.totalSum = Money.formatStringToBigDecimal(params.totalSum?:null)
        invoicePurchaseArchiveInstance.taxFreeSum = Money.formatStringToBigDecimal(params.taxFreeSum?:null)
        invoicePurchaseArchiveInstance.taxPriceSum = Money.formatStringToBigDecimal(params.taxPriceSum?:null)
        invoicePurchaseArchiveInstance.admissionCounterNumberView = InvoicePurchaseArchive.createAdmissionCounterNumberView(invoiceYear, invoicePurchaseArchiveInstance.admissionCounterNumber)

        invoicePurchaseArchiveInstance.validate()

        if (invoicePurchaseArchiveInstance.hasErrors()) {
            List<InvoicePurchaseArchive> proInvoices = InvoicePurchaseArchive.findAllByIsProInvoiceAndRefInvoice(true,null)
            render view: 'newImport',
                    model: [invoicePurchaseArchiveInstance:invoicePurchaseArchiveInstance,
                            proInvoices: proInvoices,
                    ]
            return
        }

        // Found out real mime type and set custom name if submitted
        // documentFile will automatically bound with domain property
        MultipartHttpServletRequest multiRequest
        if (request instanceof MultipartHttpServletRequest){
            multiRequest = (MultipartHttpServletRequest)request

            def file = multiRequest.getFile('documentFile')
            def mime = documentFileService.probeContentType(file.getBytes())
            invoicePurchaseArchiveInstance.mimeType = mime
            if(params.documentName.equals("")){
                invoicePurchaseArchiveInstance.documentName = file.originalFilename
            }
        }

        // Set the taxes individually
        def taxes = findByRegex(/tax\d+/,params)
        taxes.each {k,v->
            if(!v.equals("")) {
                if(invoicePurchaseArchiveInstance.taxes == null) {
                    invoicePurchaseArchiveInstance.taxes = new HashMap<Taxes, BigDecimal>()
                }
                switch (k) {
                    case "tax0":
                        invoicePurchaseArchiveInstance.taxes.put("ZERO",Money.formatStringToBigDecimal(v))
                        break
                    case 'tax5':
                        invoicePurchaseArchiveInstance.taxes.put("FIVE",Money.formatStringToBigDecimal(v))
                        break
                    case 'tax18':
                        invoicePurchaseArchiveInstance.taxes.put("EIGHTEEN",Money.formatStringToBigDecimal(v))
                        break
                }
            }
        }

        if(invoicePurchaseArchiveInstance.save(flush: true)){
            if(!invoicePurchaseArchiveInstance.isProInvoice){
                invoiceCounterService.incrementPurchaseInvoiceCounterNumber(invoiceYear)
            }
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'invoicePurchaseArchive.label', default: 'InvoicePurchaseArchive'), invoicePurchaseArchiveInstance.invoiceNumber])
                redirect invoicePurchaseArchiveInstance
            }
            '*' { respond invoicePurchaseArchiveInstance, [status: CREATED] }
        }
    }

    def edit(InvoicePurchaseArchive invoicePurchaseArchiveInstance) {
        List<InvoicePurchaseArchive> proInvoices = InvoicePurchaseArchive.findAllByIsProInvoiceAndRefInvoice(true,null)
        def admissionYear = new Date(year:invoicePurchaseArchiveInstance.invoiceYear-1900)
        render view: 'edit',
                model: [invoicePurchaseArchiveInstance:invoicePurchaseArchiveInstance,
                        proInvoices: proInvoices,
                        admissionYear: admissionYear
                ]
    }

    @Transactional
    def update(InvoicePurchaseArchive invoicePurchaseArchiveInstance) {
        if (invoicePurchaseArchiveInstance == null) {
            notFound()
            return
        }

        Long invoiceYear = Long.parseLong(params.admissionYear_year)
        invoicePurchaseArchiveInstance.invoiceYear = invoiceYear
        invoicePurchaseArchiveInstance.totalSum = Money.formatStringToBigDecimal(params.totalSum?:null)
        invoicePurchaseArchiveInstance.taxFreeSum = Money.formatStringToBigDecimal(params.taxFreeSum?:null)
        invoicePurchaseArchiveInstance.taxPriceSum = Money.formatStringToBigDecimal(params.taxPriceSum?:null)
        invoicePurchaseArchiveInstance.admissionCounterNumberView = InvoicePurchaseArchive.createAdmissionCounterNumberView(invoiceYear,invoicePurchaseArchiveInstance.admissionCounterNumber)

        invoicePurchaseArchiveInstance.validate()

        if (invoicePurchaseArchiveInstance.hasErrors()) {
            List<InvoicePurchaseArchive> proInvoices = InvoicePurchaseArchive.findAllByIsProInvoiceAndRefInvoice(true,null)
            render view: 'edit',
                    model: [invoicePurchaseArchiveInstance:invoicePurchaseArchiveInstance,
                            proInvoices: proInvoices,
                    ]
            return
        }

        def taxes = findByRegex(/tax\d+/,params)
        taxes.each {k,v->
            if(!v.equals("")) {
                if(invoicePurchaseArchiveInstance.taxes == null) {
                    invoicePurchaseArchiveInstance.taxes = new HashMap<Taxes, BigDecimal>()
                }
                switch (k) {
                    case "tax0":
                        invoicePurchaseArchiveInstance.taxes.put("ZERO",Money.formatStringToBigDecimal(v))
                        break
                    case 'tax5':
                        invoicePurchaseArchiveInstance.taxes.put("FIVE",Money.formatStringToBigDecimal(v))
                        break
                    case 'tax18':
                        invoicePurchaseArchiveInstance.taxes.put("EIGHTEEN",Money.formatStringToBigDecimal(v))
                        break
                }
            }
        }


        if(invoicePurchaseArchiveInstance.isDirty('refInvoice')){
            invoiceService.beforeUpdateInvoicePurchaseArchive(invoicePurchaseArchiveInstance)
        }

        if(invoicePurchaseArchiveInstance.save(flush: true)){
            if(invoicePurchaseArchiveInstance.isDirty('admissionCounterNumber')){
                invoiceCounterService.setPurchaseInvoiceCounter(invoiceYear)
            }
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'InvoicePurchaseArchive.label', default: 'InvoicePurchaseArchive'), invoicePurchaseArchiveInstance.id])
                redirect invoicePurchaseArchiveInstance
            }
            '*' { respond invoicePurchaseArchiveInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(InvoicePurchaseArchive invoicePurchaseArchiveInstance) {

        if (invoicePurchaseArchiveInstance == null) {
            notFound()
            return
        }

        invoicePurchaseArchiveInstance.delete flush: true
        // if delete was successful
        invoiceCounterService.setUpPurchaseInvoiceCounter()

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'InvoicePurchaseArchive.label', default: 'InvoicePurchaseArchive'), invoicePurchaseArchiveInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }

igor/InvoiceCreator/grails-app/views/invoicePurchaseArchive/_editFileForm.gsp
<g:if test="${invoicePurchaseArchiveInstance?.documentFile}">
    <div class="fieldcontain">
        <span id="documentFile-label" class="property-label"><g:message code="invoicePurchaseArchive.documentFile.label" default="Document File" /></span>
        <span  class="property-value"><g:link controller="invoicePurchaseArchive" action="showInvoicePurchaseArchiveFile" target="_blank"
                                              id="${invoicePurchaseArchiveInstance?.id}">
            ${invoicePurchaseArchiveInstance?.documentName?:'Invoice Document'}
        </g:link>
        </span>
    </div>
</g:if>
<g:else>
    <div class="fieldcontain ${hasErrors(bean: invoicePurchaseArchiveInstance, field: 'documentFile', 'error')}">
        <span class="property-label">
            <label for="documentFile">
                <g:message code="invoicePurchaseArchive.documentFile.label" default="Document File" />
            </label>
        </span>
        <span class="property-value">
            <input type="file" id="documentFile" name="documentFile" onchange="setFileName(this,'documentName')" />
        </span>
    </div>
</g:else>

<g:if test="${invoicePurchaseArchiveInstance?.documentName}">
    <div class="fieldcontain">
        <span id="documentName-label" class="property-label"><g:message code="invoicePurchaseArchive.documentName.label" default="Document Name" /></span>

        <span class="property-value" aria-labelledby="documentName-label"><g:fieldValue bean="${invoicePurchaseArchiveInstance}" field="documentName"/></span>

    </div>
</g:if>
<g:else>
    <div class="fieldcontain ${hasErrors(bean: invoicePurchaseArchiveInstance, field: 'documentName', 'error')}">
        <span class="property-label">
            <label for="documentName">
                <g:message code="invoicePurchaseArchive.documentName.label" default="Document Name" />
            </label>
        </span>
        <span class="property-value">
            <g:textField class="wider-fields" name="documentName" id="documentName" value="${invoicePurchaseArchiveInstance?.documentName}"/>
        </span>
    </div>
</g:else>

<g:if test="${invoicePurchaseArchiveInstance?.documentFile}">
    <div class="itemButtons">

        <input id="deleteFile" type="button" value="Delete File" class="buttonsMine deleteButton"
               onclick="deleteInvoicePurchaseArchiveFile(${invoicePurchaseArchiveInstance.id})"/>
    </div>
</g:if>

igor/InvoiceCreator/grails-app/views/invoicePurchaseArchive/_fileForm.gsp
<div class="fieldcontain ${hasErrors(bean: invoicePurchaseArchiveInstance, field: 'documentFile', 'error')}">
    <span class="property-label required">
        <label for="documentFile">
            <g:message code="invoiceArchive.documentFile.label" default="Document File" />
        </label>
    </span>
    <span class="property-value">
        <input type="file" required=""
               id="documentFile" name="documentFile" onchange="setFileName(this,'documentName')" />
    </span>
</div>

<div class="fieldcontain ${hasErrors(bean: invoicePurchaseArchiveInstance, field: 'documentName', 'error')}">
    <span class="property-label required">
        <label for="documentName">
            <g:message code="invoiceArchive.documentName.label" default="Document Name" />
        </label>
    </span>
    <span class="property-value">
        <g:textField class="wider-fields" required=""
                     name="documentName" id="documentName" value="${invoicePurchaseArchiveInstance?.documentName}"/>
    </span>
</div>

igor/InvoiceCreator/grails-app/views/invoicePurchaseArchive/edit.gsp
<%@ page import="com.genrep.invoiceRepository.InvoicePurchaseArchive" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'invoicePurchaseArchive.label', default: 'InvoicePurchaseArchive')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
        <asset:javascript src="invoice.js"/>
	</head>
	<body>
		<div class="nav" role="navigation">
			<ul>
                <li><a class="menuButton" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="menuButton" action="index"><g:message code="invoiceArchive.button.index" default="List Of Imported Invoices"/></g:link></li>
                <li><g:link class="menuButton" action="newImport"><g:message code="invoiceArchive.button.newImport"
                                                                             default="New Import"/></g:link></li>
            </ul>
		</div>
		<div id="edit-invoicePurchaseArchive" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${invoicePurchaseArchiveInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${invoicePurchaseArchiveInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
            <g:uploadForm url="[resource:invoicePurchaseArchiveInstance, action:'update']" method="post">
                <g:hiddenField name="version" value="${invoicePurchaseArchiveInstance?.version}" />
                <fieldset class="form">
                    <g:render template="editForm"/>
                </fieldset>
                <fieldset class="form">
                    <div id="editFileForm">
                        <g:render template="editFileForm"/>
                    </div>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="update" class="save" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:uploadForm>
		</div>
	</body>
</html>

igor/InvoiceCreator/grails-app/views/invoicePurchaseArchive/index.gsp
<%@ page import="com.genrep.client.Client; com.genrep.invoiceRepository.InvoicePurchaseArchive" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'invoicePurchaseArchive.label', default: 'InvoicePurchaseArchive')}" />
    <title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
<a href="#list-invoicePurchaseArchive" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
    <ul>
        <li><a class="menuButton" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="menuButton" action="newImport"><g:message code="invoiceArchive.button.newImport"
                                                                     default="New Import"/></g:link></li>
    </ul>
</div>
<div id="list-invoicePurchaseArchive" class="content scaffold-list" role="main">
    <h1><g:link controller="invoicePurchaseArchive" action="index">
        <g:message code="default.list.label" args="[entityName]" />
    </g:link>
    </h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>

            <g:sortableColumn property="vendor" title="${message(code: 'invoicePurchaseArchive.vendor.label', default: 'Vendor')}"/>

            <g:sortableColumn property="documentName" title="${message(code: 'invoicePurchaseArchive.documentName.label', default: 'Name')}" />

            <g:sortableColumn property="invoiceYear,admissionCounterNumber" title="${message(code: 'invoicePurchaseArchive.admissionCounterNumberView.label', default: 'Admission Number')}" />

            <g:sortableColumn property="invoiceNumber" title="${message(code: 'invoicePurchaseArchive.invoiceNumber.label', default: 'Invoice Number')}" />

            <g:sortableColumn property="totalSum" title="${message(code: 'invoicePurchaseArchive.totalSum.label', default: 'Total Sum')}" />

            <g:sortableColumn property="currency" title="${message(code: 'invoicePurchaseArchive.inCurrency.label', default: 'Currency')}" />

            <g:sortableColumn property="issueDate" title="${message(code: 'invoicePurchaseArchive.issueDate.label', default: 'Date ')}" />
        </tr>
        </thead>
        <tbody>
        <g:each in="${invoicePurchaseArchiveInstanceList}" status="i" var="invoicePurchaseArchiveInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td>${com.genrep.vendor.Vendor.get(invoicePurchaseArchiveInstance?.vendor?.id)}</td>

                <td><g:link action="show" id="${invoicePurchaseArchiveInstance.id}">
                    ${fieldValue(bean: invoicePurchaseArchiveInstance, field: "documentName")}
                </g:link></td>

                <td>${fieldValue(bean: invoicePurchaseArchiveInstance, field: "admissionCounterNumberView")}</td>

                <td>${fieldValue(bean: invoicePurchaseArchiveInstance, field: "invoiceNumber")}</td>

                <td>${invoicePurchaseArchiveInstance?.totalSum?.decodeDecimalNumber()}</td>

                <td>${fieldValue(bean: invoicePurchaseArchiveInstance, field: "inCurrency")}</td>

                <td>${formatDate(date: invoicePurchaseArchiveInstance?.issueDate, format: 'dd/MM/yyyy')}</td>
            </tr>
        </g:each>
        </tbody>
    </table>
    <div class="pagination">
        <g:paginate total="${invoicePurchaseArchiveInstanceCount ?: 0}" />
    </div>
</div>
</body>
</html>

igor/InvoiceCreator/grails-app/views/invoicePurchaseArchive/newImport.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'invoicePurchaseArchive.label', default: 'InvoicePurchaseArchive')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
        <asset:javascript src="invoice.js"/>
	</head>
	<body>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="menuButton" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="menuButton" action="index"><g:message code="invoiceArchive.button.index" default="List Of Imported Invoices"/></g:link></li>

            </ul>
		</div>
		<div id="create-invoicePurchaseArchive" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${invoicePurchaseArchiveInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${invoicePurchaseArchiveInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:uploadForm action="save" method="post" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
                <fieldset class="form">
                    <g:render template="fileForm"/>
                </fieldset>
				<fieldset class="buttons">
					<g:submitButton name="save" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:uploadForm>
		</div>
	</body>
</html>