igor/InvoiceCreator/grails-app/domain/com/genrep/statements/BankStatement.groovy
package com.genrep.statements

import com.genrep.account.BankAccount

class BankStatement {

    static constraints = {
        ownerOfStatement()
        bankStatementId()
        issueDate()
        balanceBefore()
        balanceAfter()
        currency(nullable:true)
        bankStatementDocId(nullable:true)
        items(nullable: true)
    }

    // This bank account should be the same as one of the creditor or debtor from the transcation
    // fields of BankStatementItem
    BankAccount ownerOfStatement
    String bankStatementId
    Date issueDate
    BigDecimal balanceBefore
    BigDecimal balanceAfter
    Currency currency
    // If the invoice is imported from file
    String bankStatementDocId
    String bankAccountNumber // For parsing

    static hasMany = [items:BankStatementItem]
    static transients = ['bankAccountNumber']

    int findLargestOrderNumber(){
        int largest = 0
        for( item in items ){
            if(item.orderNumber > largest){
                largest = item.orderNumber
            }
        }
        return largest
    }
}

igor/InvoiceCreator/grails-app/domain/com/genrep/statements/BankStatementDoc.groovy
package com.genrep.statements

/**
 * This class is used for imported Bank Statements from a matching standard
 */
class BankStatementDoc {

    static constraints = {
        uuid()
        documentFile()
        documentName(nullable: true, blank:true)
        mimeType(nullable:true,blank:true)
        isTransferred()
        issueDate(nullable: true)
        dateCreated()
    }

    String uuid = UUID.randomUUID()
    byte [] documentFile
    String documentName
    String mimeType
    boolean isTransferred = false

    Date issueDate
    Date dateCreated

    static mapWith = "mongo"

    static mapping = {
        collection "BankStatementDocuments"
//        database "InvoiceRepository"
    }
}

igor/InvoiceCreator/grails-app/controllers/com/genrep/statements/BankStatementDocController.groovy
package com.genrep.statements

import com.genrep.sharedHelpers.DocumentFileService
import grails.converters.JSON
import org.springframework.web.multipart.MultipartHttpServletRequest

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class BankStatementDocController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    DocumentFileService documentFileService
    BankStatementService bankStatementService

    /**
     *
     * Regular actions
     */
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond BankStatementDoc.list(params), model:[bankStatementDocInstanceCount: BankStatementDoc.count()]
    }

    def show(BankStatementDoc bankStatementDocInstance) {
        respond bankStatementDocInstance
    }

    def create() {
        respond new BankStatementDoc(params)
    }

    @Transactional
    def save(BankStatementDoc bankStatementDocInstance) {
        if (bankStatementDocInstance == null) {
            notFound()
            return
        }

        if (bankStatementDocInstance.hasErrors()) {
            respond bankStatementDocInstance.errors, view:'create'
            return
        }

        MultipartHttpServletRequest multiRequest
        if (request instanceof MultipartHttpServletRequest){
            multiRequest = (MultipartHttpServletRequest)request

            def file = multiRequest.getFile('documentFile')
            def mime = documentFileService.probeContentType(file.getBytes())
            if(params.documentName.equals("")){
                bankStatementDocInstance.documentName = file.originalFilename
            }else{
                bankStatementDocInstance.documentName = params.documentName
            }
            bankStatementDocInstance.mimeType = mime
        }

        bankStatementDocInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'bankStatementDoc.label', default: 'BankStatementDoc'), bankStatementDocInstance.id])
                redirect bankStatementDocInstance
            }
            '*' { respond bankStatementDocInstance, [status: CREATED] }
        }
    }

    def edit(BankStatementDoc bankStatementDocInstance) {
        respond bankStatementDocInstance
    }

    @Transactional
    def update(BankStatementDoc bankStatementDocInstance) {
        if (bankStatementDocInstance == null) {
            notFound()
            return
        }

        if (bankStatementDocInstance.hasErrors()) {
            respond bankStatementDocInstance.errors, view:'edit'
            return
        }

        bankStatementDocInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'BankStatementDoc.label', default: 'BankStatementDoc'), bankStatementDocInstance.id])
                redirect bankStatementDocInstance
            }
            '*'{ respond bankStatementDocInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(BankStatementDoc bankStatementDocInstance) {

        if (bankStatementDocInstance == null) {
            notFound()
            return
        }

        def docUuid = bankStatementDocInstance.uuid
        bankStatementDocInstance.delete flush:true

        // if it successfull delete in hibernate also.This should change in future.
        // TODO: DA SE REVDIRA OVA ODNESUVANJE
        try {
            def bs = BankStatement.findByBankStatementDocId(docUuid.toString())
            bs.delete flush: true
        }
        catch(Exception e){
            log.error "Problem removing BankStatement. If the error is NullPointerException then ignore this."
            log.error(e.fillInStackTrace())
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'BankStatementDoc.label', default: 'BankStatementDoc'), bankStatementDocInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    /**
     *
     * Action related to Bank Statement
     */

    def showBankStatementDetails(BankStatementDoc bankStatementDocInstance){

        if(bankStatementDocInstance){
            //check if it is parsed
            def bs = BankStatement.findByBankStatementDocId(bankStatementDocInstance.uuid)
            if(bs){
                //render bankStatement
                def total = bs.balanceAfter-bs.balanceBefore
                render view: 'showBankStatementDetails', model: [bankStatementInstance: bs, saved:true, total:total,
                              bankStatementDocInstance: bankStatementDocInstance]
            }else{
                //parse document
                try {
                    bs = bankStatementService.parseBankStatementDoc(bankStatementDocInstance)
                    session.setAttribute('bankStatementInstance', bs)
                    def total = bs.balanceAfter - bs.balanceBefore
                    render view: 'showBankStatementDetails', model: [bankStatementInstance: bs, total:total]
                }
                catch(Exception e){
                    log.error "Error while parsing document."
                    log.error e.fillInStackTrace()
                    notFound()
                }

            }
        }
    }

    def saveBankStatement(){
        BankStatement bankStatementInstance = session.bankStatementInstance

        if (bankStatementInstance == null) {
            notFound()
            return
        }

        if (bankStatementInstance.hasErrors()) {
            bankStatementInstance.errors.allErrors.each {
                println it
            }
            respond bankStatementInstance.errors, view:'list'
            return
        }

        def total = bankStatementInstance.balanceAfter-bankStatementInstance.balanceBefore

        bankStatementService.preSavingBankStatement(bankStatementInstance)
        if(bankStatementService.saveBankStatement(bankStatementInstance)){
            bankStatementService.postSavingBankStatement(bankStatementInstance)
            flash.message = message(code: 'default.created.message', args: [message(code: 'bankStatement.label', default: 'BankStatement'), bankStatementInstance.id])
            render view: 'showBankStatementDetails', model: [bankStatementInstance: bankStatementInstance, saved:true, total:total]

        }else{
            render view:'showBankStatementDetails', model:[bankStatementInstance:bankStatementInstance,total:total]
        }

    }

    /**
     *
     * MultiImport actions
     */


    def multiImport(){
        session.setAttribute('uploadedStatements',[:])
        return
    }


    def saveMultiImport(){
        def uploadedStatements = session.getAttribute("uploadedStatements") as Map
        try {
            uploadedStatements.each { k, BankStatementDoc v ->
                v.save flush: true
            }
        }
        catch(Exception e){
            log.error "Cannot save multiple imports of statements."
            log.error e.fillInStackTrace()
        }

        flash.message = message(code: 'bankStatementDoc.multiImport.success', default: 'Upload was successful.')
        redirect action:"index", method:"GET"
    }

    def uploadStatementDoc = {

        MultipartHttpServletRequest multiRequest
        if (request instanceof MultipartHttpServletRequest){
            multiRequest = (MultipartHttpServletRequest)request
        }
        else {
            return
        }

        BankStatementDoc bankStatementDocInstance = new BankStatementDoc()

        def file = multiRequest.getFile('documentFile')
        def mime = documentFileService.probeContentType(file.getBytes())
        if(params.documentName.equals("")){
            bankStatementDocInstance.documentName = file.originalFilename
        }else{
            bankStatementDocInstance.documentName = params.documentName
        }
        if(!params.issueDate.equals("")){
            bankStatementDocInstance.issueDate = Date.parse("dd.MM.yyyy",params.issueDate)
        }
        bankStatementDocInstance.mimeType = mime
        bankStatementDocInstance.documentFile = file.bytes


        def uploadedStatements = session.getAttribute("uploadedStatements") as Map
        def uuid = UUID.randomUUID().toString()
        uploadedStatements.put(uuid,bankStatementDocInstance)

        /*********************
         generate response
         **********************/

        def tableRow = """
            <tr id="$uuid">
            <td>$bankStatementDocInstance.documentName</a></td>
            <td>${formatDate(date:bankStatementDocInstance?.issueDate,format:"dd.MM.yyyy")}</td>
            <td><input type="button" value="Remove me" onclick="removeStatementFile('$uuid')"/></td>
            </tr>
        """

        def statementsList = [] << [
                doc_name:bankStatementDocInstance.documentName,
                issue_date:bankStatementDocInstance?.issueDate,
                uuid:uuid,
                table_row: tableRow
        ]

        withFormat {
            json {
                render statementsList as JSON
            }
        }
    }

    def removeStatementDoc = {
        if(params.uuid.equals("")){
            return
        }else{
            def uploadedStatements = session.getAttribute("uploadedStatements") as Map
            def uuid = params.uuid

            if(uploadedStatements.containsKey(uuid)){
                uploadedStatements.remove(uuid)
                render status: OK
            }
        }
    }


    /**
     *  Helper actions
     */

    protected void notFound() {
        request.withFormat {
            form multipartForm {

igor/InvoiceCreator/grails-app/views/bankStatementDoc/_fileForm.gsp
<div id="uploadForm">
    <div class="fieldcontain">
        <span class="property-label required">
            <label for="statementDoc">
                <g:message code="bankStatementDoc.documentFile.label" default="Statement Doc" />
            </label>
        </span>
        <span class="property-value">
            <input type="file" id="documentFile" name="documentFile" onchange="setFileName(this,'documentName')" />
        </span>

    </div>

    <div class="fieldcontain">
        <span class="property-label">
            <label for="documentName">
                <g:message code="bankStatementDocInstance.documentName.label" default="Document Name" />
            </label>
        </span>
        <span class="property-value">
            <g:textField class="wider-fields" name="documentName" id="documentName"/>
        </span>
    </div>

    <div class="fieldcontain">
        <span class="property-label">
            <label for="issueDate">
                <g:message code="bankStatementDoc.issueDate.label" default="Issue Date" />
            </label>
        </span>
        <span class="property-value">
            <input type="text" name="issueDate" id="issueDate" class="date"/>
        </span>
    </div>

</div>

<div class="fieldcontain">
    <span class="property-value">
        <input type='button' class="buttonsMine" name='submit' value='Add Statement' onclick="uploadStatementFile()" />
    </span>
</div>

<div class="fieldcontain">
    <span class="property-value">
        <div id="progressBar">
            <div>
            </div>
        </div>
    </span>
</div>

<div id="uploadedStatements" class="document-file-div">
    <table id="statementsTable" class="statementsTable">
        <tbody></tbody>
    </table>
</div>

igor/InvoiceCreator/grails-app/views/bankStatementDoc/_form.gsp
<%@ page import="com.genrep.statements.BankStatementDoc" %>


<div class="fieldcontain ${hasErrors(bean: bankStatementDocInstance, field: 'documentFile', 'error')}">
    <span class="property-label required">
        <label for="statementDoc">
            <g:message code="bankStatementDoc.statementDoc.label" default="Statement Doc" />
        </label>
    </span>
    <span class="property-value">
        <input type="file" id="documentFile" name="documentFile" />
    </span>

</div>

<div class="fieldcontain ${hasErrors(bean: bankStatementDocInstance, field: 'documentName', 'error')}">
    <span class="property-label">
        <label for="documentName">
            <g:message code="bankStatementDocInstance.documentName.label" default="Document Name" />
        </label>
    </span>
    <span class="property-value">
        <g:textField class="wider-fields" name="documentName" id="documentName" value="${bankStatementDocInstance?.documentName}"/>
    </span>
</div>

<div class="fieldcontain ${hasErrors(bean: bankStatementDocInstance, field: 'issueDate', 'error')} ">
    <span class="property-label">
        <label for="issueDate">
            <g:message code="bankStatementDoc.issueDate.label" default="Issue Date" />
        </label>
    </span>
    <span class="property-value">
        <input type="text" name="issueDate" id="issueDate" class="date"
               value="${formatDate(date:bankStatementDocInstance.issueDate,format: 'dd.MM.yyyy')}"/>
    </span>
</div>

igor/InvoiceCreator/grails-app/views/bankStatementDoc/_tableOfBankStatementItems.gsp
<table>
    <thead>
    <tr>

        %{--<th><g:message code="statements.item.orderNumber" default="No."/></th>--}%
        <th><g:message code="statements.item.publicEntity" default="Public Entity"/></th>
        <th><g:message code="statements.item.publicEntityBankAccountNumber" default="Bank Acc. No."/></th>
        <th><g:message code="statements.item.transferSum" default="Transfer Sum"/></th>
        <th><g:message code="statements.item.transcationCode" default="Trans. Code"/></th>
        <th><g:message code="statements.item.shortDescription" default="Description"/></th>
        <th><g:message code="statements.item.borrowingCode" default="Borrowal"/></th>
        <th colspan="2"><g:message code="statements.item.approvalCode" default="Approval"/></th>

    </tr>
    </thead>
    <tbody>
    <g:each in="${bankStatementInstance?.items?.sort{it.orderNumber}}" status="i" var="bankStatementItem">
        <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

            %{--<td>${bankStatementItem?.orderNumber?:i}</td>--}%
            <td>${bankStatementItem.publicEntity}</td>
            <td>${bankStatementItem.publicEntityBankAccountNumber}</td>
            <td>${bankStatementItem.transferSum.decodeDecimalNumber()}</td>
            <td>${bankStatementItem.transactionCode}</td>
            <td>${bankStatementItem.shortDescription}</td>
            <td>${bankStatementItem.borrowingCode}</td>
            <td>${bankStatementItem.approvalCode}</td>
            <td><g:if test="${form=='editBankStatementItems'}">
                <input id="removeItemButton" type="button" value="Remove Item"
                       onclick="removeBankStatementItem(${bankStatementItem.id},'${form}')"/>
            </g:if></td>
        </tr>
    </g:each>
    </tbody>
</table>

igor/InvoiceCreator/grails-app/views/bankStatementDoc/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'bankStatementDoc.label', default: 'BankStatementDoc')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
        <asset:javascript src="statement.js"/>
	</head>
	<body>
		<a href="#create-bankStatementDoc" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
                <li><a class="menuButton" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="menuButton" action="index"><g:message code="bankStatmentDoc.list" default="List Bank Statements" /></g:link></li>
			</ul>
		</div>
		<div id="create-bankStatementDoc" class="content scaffold-create" role="main">
			<h1><g:message code="bankStatementDoc.create.label" default="Enter New Bank Statement" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${bankStatementDocInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${bankStatementDocInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:bankStatementDocInstance, action:'save']"  enctype="multipart/form-data">
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

igor/InvoiceCreator/grails-app/views/bankStatementDoc/edit.gsp
<%@ page import="com.genrep.statements.BankStatementDoc" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'bankStatementDoc.label', default: 'BankStatementDoc')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
        <asset:javascript src="statement.js"/>
	</head>
	<body>
		<a href="#edit-bankStatementDoc" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
                <li><a class="menuButton" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="menuButton" action="create"><g:message code="bankStatmentDoc.new" default="New Bank Statement" /></g:link></li>
                <li><g:link class="menuButton" action="index"><g:message code="bankStatmentDoc.list" default="List Bank Statements" /></g:link></li>
            </ul>
		</div>
		<div id="edit-bankStatementDoc" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${bankStatementDocInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${bankStatementDocInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:bankStatementDocInstance, action:'update']" method="PUT"  enctype="multipart/form-data">
				<g:hiddenField name="version" value="${bankStatementDocInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

igor/InvoiceCreator/grails-app/views/bankStatementDoc/index.gsp
<%@ page import="com.genrep.statements.BankStatementDoc" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'bankStatementDoc.label', default: 'BankStatementDoc')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
        <asset:javascript src="statement.js"/>
	</head>
	<body>

		<div class="nav" role="navigation">
			<ul>
				<li><a class="menuButton" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><a class="menuButton" href="${createLink(uri: '/statements')}"><g:message code="bankStatement.home.label" default="Statements"/></a></li>
				<li><g:link class="menuButton" action="create"><g:message code="bankStatmentDoc.new" default="Import Bank Statement" /></g:link></li>
				<li><g:link class="menuButton" action="multiImport"><g:message code="bankStatmentDoc.multiImport" default="Import Multi Statements" /></g:link></li>
			</ul>
		</div>
		<div id="list-bankStatementDoc" class="content scaffold-list" role="main">
			<h1><g:message code="bankStatementDoc.list.label" default="Imported Documents Of Bank Statements" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>

						<g:sortableColumn property="statementDoc" title="${message(code: 'bankStatementDoc.documentFile.label', default: 'Statement Doc')}" />
					
						<g:sortableColumn property="isTransferred" title="${message(code: 'bankStatementDoc.isTransferred.label', default: 'Is Transferred')}" />
					
						<g:sortableColumn property="issueDate" title="${message(code: 'bankStatementDoc.issueDate.label', default: 'Issue Date')}" />
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'bankStatementDoc.dateCreated.label', default: 'Date Created')}" />

                        <th colspan="2"><g:message code="statements.action" default="Action"/></th>
					</tr>
				</thead>
				<tbody>
				<g:each in="${bankStatementDocInstanceList}" status="i" var="bankStatementDocInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">


                        <g:if test="${bankStatementDocInstance.mimeType!=null}">
                        <td><g:link class="doc-${bankStatementDocInstance.mimeType.split('/')[1]}"
                                controller="worker" action="readFileFromMongoDb" target="_blank"
                                params="[docMongoId: bankStatementDocInstance.uuid, domain: 'BankStatementDoc']">
                            ${bankStatementDocInstance?.documentName}
                        </g:link></td>
                        </g:if><g:else>
                        <td><g:link
                                    controller="worker" action="readFileFromMongoDb" target="_blank"
                                    params="[docMongoId: bankStatementDocInstance.uuid, domain: 'BankStatementDoc']">
                            ${bankStatementDocInstance?.documentName}
                        </g:link></td>
                        </g:else>

						<td><g:formatBoolean boolean="${bankStatementDocInstance.isTransferred}" /></td>
					
						<td><g:formatDate date="${bankStatementDocInstance.issueDate}" format="dd.MM.yyyy" /></td>
					
						<td><g:formatDate date="${bankStatementDocInstance.dateCreated}" format="dd.MM.yyyy" /></td>

						<td><g:link action="showBankStatementDetails" id="${bankStatementDocInstance.id}" ><g:message code="statements.action.parse" default="Show Details"/>
                        </g:link></td>

                        <td><g:form url="[resource:bankStatementDocInstance, action:'delete']" method="DELETE">
                            <fieldset class="buttons">
                                <g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                            </fieldset>
                        </g:form></td>

					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${bankStatementDocInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

igor/InvoiceCreator/grails-app/views/bankStatementDoc/multiImport.gsp
<%--
  Created by IntelliJ IDEA.
  User: igor
  Date: 9/24/14
  Time: 11:02 AM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'bankStatementDoc.label', default: 'BankStatementDoc')}" />
    <title><g:message code="default.create.label" args="[entityName]" /></title>
    <asset:javascript src="statement.js"/>
</head>
<body>

<div class="nav" role="navigation">
    <ul>
        <li><a class="menuButton" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="menuButton" action="index"><g:message code="bankStatmentDoc.list" default="List Bank Statements" /></g:link></li>
    </ul>
</div>
<div id="create-bankStatementDoc" class="content scaffold-create" role="main">
    <h1><g:message code="bankStatementDoc.multiImportlabel" default="Upload Bank Statements for import" /></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>

    <g:uploadForm action="saveMultiImport" method="post">

        <fieldset class="form">
            <g:render template="fileForm"/>
        </fieldset>

        <fieldset class="buttons">
            <g:submitButton name="saveMultiImport" class="save" value="${message(code: 'bankStatement.multiImport.create.label', default: 'Upload')}" />
        </fieldset>
    </g:uploadForm>
</div>
</body>
</html>